version: '3.1'

services:
  araneo:
    image: voko-araneo
    build: 
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - 8088:80
    depends_on:
     - abelo
    secrets:
      #- mysql_root_password
      - mysql_password         

  # saluto de abelisto al abelo:
  # servilo-nomo estas la nomo de abelo (docker ps)
  # uzanto-nomo estas "root"
  # db-nomo estas la skemo (usr_web277_1)
  # pasvorto: vd. malsupre (MYSQL_ROOT_PASSWORD)
  abelisto:
    image: adminer
    #restart: always
    environment:
      ADMINER_DESIGN: hever
    ports:
      - 8089:8080  
    depends_on:
      - abelo
 

  abelo:
    image: voko-abelo
    build: https://github.com/revuloj/voko-abelo.git
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    #expose:
    #  - 3306
    secrets:
      - mysql_root_password
      - mysql_password
    environment:
      # FARENDA: necesas aldoni tiujn informojn ankaŭ en la dosiero revodb.pm
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: usr_web277_1
      MYSQL_USER: web277
      # MYSQL_ROOT_PASSWORD: sekreto28343

secrets:
  # FARENDA:
  # necesas adapti revodb.pm por ke ĝi legu la pasvorton el /run/secrets/mysql_password
  #
  # vi povas krei taŭgajn pasvortojn per:
  #   openssl rand -base64 20 | docker secret create mysql_root_password -
  #   openssl rand -base64 20 | docker secret create mysql_password -
  mysql_root_password:
    external: true
  mysql_password:
    external: true


  


