version: '3.1'

services:
  araneo:
    image: voko-araneo
    build: 
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - 8088:80
    # depends_on:
    # - abelo

  # saluto de abelisto al abelo:
  # servilo-nomo estas la nomo de abelo (docker ps)
  # uzanto-nomo estas "root"
  # db-nomo estas la skemo (usr_web277_1)
  # pasvorto: vd. malsupre (MYSQL_ROOT_PASSWORD)
  abelisto:
    image: adminer
    #restart: always
    environment:
      ADMINER_DESIGN: hever
    ports:
      - 8089:8080      
    depends_on:
      - abelo

  abelo:
    image: voko-abelo
    build: https://github.com/revuloj/voko-abelo.git
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    #expost:
    #  - 3306
    environment:
      # ŝanĝu la pasvorton se vi lanĉas en publika ĉirkaŭaĵo...
      # necesas tion fari ankaŭ en la dosiero revodb.pm
      MYSQL_ROOT_PASSWORD: sekreto


  


