#!/usr/bin/perl
package revo::decode;

#
# revo::decode.pm
# 
# 2008-02-13 Wieland Pusch
#

use strict; use warnings;

use utf8;
use Encode;
use HTML::Entities;

######################################################################
sub rvdecode {
  my ($str) = @_;

  my $enc = "utf-8";
#  print "decode $str\n";
  $str = Encode::decode($enc, $str);

#  print "encode ".Encode::encode($enc, $str)."\n";

  # <!-- e-aj literoj -->
  my %map = (
  '&Ccirc;' => "\x{0108}",
  '&ccirc;' => "\x{0109}",
  '&Gcirc;' => "\x{011c}",
  '&gcirc;' => "\x{011d}",
  '&Hcirc;' => "\x{0124}",
  '&hcirc;' => "\x{0125}",
  '&Jcirc;' => "\x{0134}",
  '&jcirc;' => "\x{0135}",
  '&Scirc;' => "\x{015c}",
  '&scirc;' => "\x{015d}",
  '&Ubreve;' => "\x{016c}",
  '&ubreve;' => "\x{016d}",

  # <!-- francaj k.a. -->
  '&eacute;' => "\x{00e9}",
  '&Oacute;' => "\x{00d3}",
  '&oacute;' => "\x{00f3}",
  '&Agrave;' => "\x{00c0}",
  '&agrave;' => "\x{00e0}",
  '&Egrave;' => "\x{00c8}",
  '&egrave;' => "\x{00e8}",
  '&Igrave;' => "\x{00cc}",
  '&igrave;' => "\x{00ec}",
  '&Ograve;' => "\x{00d2}",
  '&ograve;' => "\x{00f2}",
  '&Ugrave;' => "\x{00d9}",
  '&ugrave;' => "\x{00f9}",

  '&Acirc;' => "\x{00c2}",
  '&acirc;' => "\x{00e2}",
  '&Ecirc;' => "\x{00ca}",
  '&ecirc;' => "\x{00ea}",
  '&Icirc;' => "\x{00ce}",
  '&icirc;' => "\x{00ee}",
  '&Ocirc;' => "\x{00d4}",
  '&ocirc;' => "\x{00f4}",
  '&Ucirc;' => "\x{00db}",
  '&ucirc;' => "\x{00fb}",

  # <!-- germanaj -->
  '&szlig;' => "\x{00df}",
  '&Auml;' => "\x{00c4}",
  '&auml;' => "\x{00e4}",
  '&Ouml;' => "\x{00d6}",
  '&ouml;' => "\x{00f6}",
  '&Uuml;' => "\x{00dc}",
  '&uuml;' => "\x{00fc}",

  # <!-- turkaj ne jam menciitaj -->
  '&Gbreve;' => "\x{011e}",
  '&gbreve;' => "\x{011f}",
  '&inodot;' => "\x{0131}",
  '&Idot;' => "\x{0130}",
  '&Scedil;' => "\x{015e}",
  '&scedil;' => "\x{015f}",
  '&Ccedil;' => "\x{00c7}",
  '&ccedil;' => "\x{00e7}",

  # <!-- diversaj -->
  '&#60;' => '&lt;',
  '&#62;' => '&gt;',
  
  '&leftquot;' => "\x{201e}",
  '&rightquot;' => "\x{201c}",
  '&mdash;' => "\x{2014}",

  '&Euml;' => "\x{00cb}",
  '&euml;' => "\x{00eb}",
  '&Iuml;' => "\x{00cf}",
  '&iuml;' => "\x{00ef}",

  '&Aring;' => "\x{00c5}",
  '&aring;' => "\x{00e5}",
  '&AElig;' => "\x{00c6}",
  '&aelig;' => "\x{00e6}",
  '&Oslash;' => "\x{00d8}",
  '&oslash;' => "\x{00f8}",

  # <!-- portugalaj, hispanaj, katalunaj -->
  '&Ntilde;' => "\x{00d1}",
  '&ntilde;' => "\x{00f1}",

  '&Atilde;' => "\x{00c3}",
  '&atilde;' => "\x{00e3}",
  '&Otilde;' => "\x{00d5}",
  '&otilde;' => "\x{00f5}",

  '&middot;' => "\x{00b7}",

  # <!-- rumanaj -->
  '&Abreve;' => "\x{0102}",
  '&abreve;' => "\x{0103}",
  '&Tcedil;' => "\x{0162}",
  '&tcedil;' => "\x{0163}",

  # <!-- grekaj -->
  '&Alfa;' => "\x{0391}",
  '&alfa;' => "\x{03b1}",
  '&alfa_acute;' => "\x{1f71}",
  '&Alfa_acute;' => "\x{1fbb}",
  '&alfa_acute_subj;' => "\x{1fb4}",
  '&alfa_breve;' => "\x{1fb0}",
  '&Alfa_breve;' => "\x{1fb8}",
  '&alfa_circ;' => "\x{1fb6}",
  '&alfa_circ_subj;' => "\x{1fb7}",
  '&alfa_densa;' => "\x{1f01}",
  '&Alfa_densa;' => "\x{1f09}",
  '&alfa_densa_acute;' => "\x{1f05}",
  '&Alfa_densa_acute;' => "\x{1f0d}",
  '&alfa_densa_acute_subj;' => "\x{1f85}",
  '&Alfa_densa_acute_Subj;' => "\x{1f8d}",
  '&alfa_densa_circ;' => "\x{1f07}",
  '&Alfa_densa_circ;' => "\x{1f0f}",
  '&alfa_densa_circ_subj;' => "\x{1f87}",
  '&Alfa_densa_circ_Subj;' => "\x{1f8f}",
  '&alfa_densa_grave;' => "\x{1f03}",
  '&Alfa_densa_grave;' => "\x{1f0b}",
  '&alfa_densa_grave_subj;' => "\x{1f83}",
  '&Alfa_densa_grave_Subj;' => "\x{1f8b}",
  '&alfa_densa_subj;' => "\x{1f81}",
  '&Alfa_densa_Subj;' => "\x{1f89}",
  '&alfa_grave;' => "\x{1f70}",
  '&Alfa_grave;' => "\x{1fba}",
  '&alfa_grave_subj;' => "\x{1fb2}",
  '&alfa_makron;' => "\x{1fb1}",
  '&Alfa_makron;' => "\x{1fb9}",
  '&alfa_psili;' => "\x{1f00}",
  '&Alfa_psili;' => "\x{1f08}",
  '&alfa_psili_acute;' => "\x{1f04}",
  '&Alfa_psili_acute;' => "\x{1f0c}",
  '&alfa_psili_acute_subj;' => "\x{1f84}",
  '&Alfa_psili_acute_Subj;' => "\x{1f8c}",
  '&alfa_psili_circ;' => "\x{1f06}",
  '&Alfa_psili_circ;' => "\x{1f0e}",
  '&alfa_psili_circ_subj;' => "\x{1f86}",
  '&Alfa_psili_circ_Subj;' => "\x{1f8e}",
  '&alfa_psili_grave;' => "\x{1f02}",
  '&Alfa_psili_grave;' => "\x{1f0a}",
  '&alfa_psili_grave_subj;' => "\x{1f82}",
  '&Alfa_psili_grave_Subj;' => "\x{1f8a}",
  '&alfa_psili_subj;' => "\x{1f80}",
  '&Alfa_psili_Subj;' => "\x{1f88}",
  '&alfa_subj;' => "\x{1fb3}",
  '&Alfa_Subj;' => "\x{1fbc}",
  '&Alfa_ton;' => "\x{0386}",
  '&alfa_ton;' => "\x{03ac}",

  '&Beta;' => "\x{0392}",
  '&beta;' => "\x{03b2}",

  '&Gamma;' => "\x{0393}",
  '&gamma;' => "\x{03b3}",

  '&Delta;' => "\x{0394}",
  '&delta;' => "\x{03b4}",

  '&Epsilon;' => "\x{0395}",
  '&epsilon;' => "\x{03b5}",
  '&epsilon_acute;' => "\x{1f73}",
  '&Epsilon_acute;' => "\x{1fc9}",
  '&epsilon_densa;' => "\x{1f11}",
  '&Epsilon_densa;' => "\x{1f19}",
  '&epsilon_densa_acute;' => "\x{1f15}",
  '&Epsilon_densa_acute;' => "\x{1f1d}",
  '&epsilon_densa_grave;' => "\x{1f13}",
  '&Epsilon_densa_grave;' => "\x{1f1b}",
  '&epsilon_grave;' => "\x{1f72}",
  '&Epsilon_grave;' => "\x{1fc8}",
  '&epsilon_psili;' => "\x{1f10}",
  '&Epsilon_psili;' => "\x{1f18}",
  '&epsilon_psili_acute;' => "\x{1f14}",
  '&Epsilon_psili_acute;' => "\x{1f1c}",
  '&epsilon_psili_grave;' => "\x{1f12}",
  '&Epsilon_psili_grave;' => "\x{1f1a}",
  '&Epsilon_ton;' => "\x{0388}",
  '&epsilon_ton;' => "\x{03ad}",

  '&Zeta;' => "\x{0396}",
  '&zeta;' => "\x{03b6}",

  '&Eta;' => "\x{0397}",
  '&eta;' => "\x{03b7}",
  '&eta_acute;' => "\x{1f75}",
  '&Eta_acute;' => "\x{1fcb}",
  '&eta_acute_subj;' => "\x{1fc4}",
  '&eta_circ;' => "\x{1fc6}",
  '&eta_circ_subj;' => "\x{1fc7}",
  '&eta_densa;' => "\x{1f21}",
  '&Eta_densa;' => "\x{1f29}",
  '&eta_densa_acute;' => "\x{1f25}",
  '&Eta_densa_acute;' => "\x{1f2d}",
  '&eta_densa_acute_subj;' => "\x{1f95}",
  '&Eta_densa_acute_Subj;' => "\x{1f9d}",
  '&eta_densa_circ;' => "\x{1f27}",
  '&Eta_densa_circ;' => "\x{1f2f}",
  '&eta_densa_circ_subj;' => "\x{1f97}",
  '&Eta_densa_circ_Subj;' => "\x{1f9f}",
  '&eta_densa_grave;' => "\x{1f23}",
  '&Eta_densa_grave;' => "\x{1f2b}",
  '&eta_densa_grave_subj;' => "\x{1f93}",
  '&Eta_densa_grave_Subj;' => "\x{1f9b}",
  '&eta_densa_subj;' => "\x{1f91}",
  '&Eta_densa_Subj;' => "\x{1f99}",
  '&eta_grave;' => "\x{1f74}",
  '&Eta_grave;' => "\x{1fca}",
  '&eta_grave_subj;' => "\x{1fc2}",
  '&eta_psili;' => "\x{1f20}",
  '&Eta_psili;' => "\x{1f28}",
  '&eta_psili_acute;' => "\x{1f24}",
  '&Eta_psili_acute;' => "\x{1f2c}",
  '&eta_psili_acute_subj;' => "\x{1f94}",
  '&Eta_psili_acute_Subj;' => "\x{1f9c}",
  '&eta_psili_circ;' => "\x{1f26}",
  '&Eta_psili_circ;' => "\x{1f2e}",
  '&eta_psili_circ_subj;' => "\x{1f96}",
  '&Eta_psili_circ_Subj;' => "\x{1f9e}",
  '&eta_psili_grave;' => "\x{1f22}",
  '&Eta_psili_grave;' => "\x{1f2a}",
  '&eta_psili_grave_subj;' => "\x{1f92}",
  '&Eta_psili_grave_Subj;' => "\x{1f9a}",
  '&eta_psili_subj;' => "\x{1f90}",
  '&Eta_psili_Subj;' => "\x{1f98}",
  '&eta_subj;' => "\x{1fc3}",
  '&Eta_Subj;' => "\x{1fcc}",
  '&Eta_ton;' => "\x{0389}",
  '&eta_ton;' => "\x{03ae}",

  '&Theta;' => "\x{0398}",
  '&theta;' => "\x{03b8}",

  '&Jota;' => "\x{0399}",
  '&jota;' => "\x{03b9}",
  '&jota_acute;' => "\x{1f77}",
  '&Jota_acute;' => "\x{1fdb}",
  '&jota_breve;' => "\x{1fd0}",
  '&Jota_breve;' => "\x{1fd8}",
  '&jota_circ;' => "\x{1fd6}",
  '&jota_densa;' => "\x{1f31}",
  '&Jota_densa;' => "\x{1f39}",
  '&jota_densa_acute;' => "\x{1f35}",
  '&Jota_densa_acute;' => "\x{1f3d}",
  '&jota_densa_circ;' => "\x{1f37}",
  '&Jota_densa_circ;' => "\x{1f3f}",
  '&jota_densa_grave;' => "\x{1f33}",
  '&Jota_densa_grave;' => "\x{1f3b}",
  '&jota_grave;' => "\x{1f76}",
  '&Jota_grave;' => "\x{1fda}",
  '&jota_makron;' => "\x{1fd1}",
  '&Jota_makron;' => "\x{1fd9}",
  '&jota_psili;' => "\x{1f30}",
  '&Jota_psili;' => "\x{1f38}",
  '&jota_psili_acute;' => "\x{1f34}",
  '&Jota_psili_acute;' => "\x{1f3c}",
  '&jota_psili_circ;' => "\x{1f36}",
  '&Jota_psili_circ;' => "\x{1f3e}",
  '&jota_psili_grave;' => "\x{1f32}",
  '&Jota_psili_grave;' => "\x{1f3a}",
  '&Jota_ton;' => "\x{038a}",
  '&jota_ton;' => "\x{03af}",
  '&Jota_trema;' => "\x{03aa}",
  '&jota_trema;' => "\x{03ca}",
  '&jota_trema_acute;' => "\x{1fd3}",
  '&jota_trema_circ;' => "\x{1fd7}",
  '&jota_trema_grave;' => "\x{1fd2}",
  '&jota_trema_ton;' => "\x{0390}",

  '&Kappa;' => "\x{039a}",
  '&kappa;' => "\x{03ba}",
  '&Lambda;' => "\x{039b}",
  '&lambda;' => "\x{03bb}",
  '&My;' => "\x{039c}",
  '&my;' => "\x{03bc}",
  '&Ny;' => "\x{039d}",
  '&ny;' => "\x{03bd}",
  '&Xi;' => "\x{039e}",
  '&xi;' => "\x{03be}",

  '&Omikron;' => "\x{039f}",
  '&omikron;' => "\x{03bf}",
  '&omikron_acute;' => "\x{1f79}",
  '&Omikron_acute;' => "\x{1ff9}",
  '&omikron_densa;' => "\x{1f41}",
  '&Omikron_densa;' => "\x{1f49}",
  '&omikron_densa_acute;' => "\x{1f45}",
  '&Omikron_densa_acute;' => "\x{1f4d}",
  '&omikron_densa_grave;' => "\x{1f43}",
  '&Omikron_densa_grave;' => "\x{1f4b}",
  '&omikron_grave;' => "\x{1f78}",
  '&Omikron_grave;' => "\x{1ff8}",
  '&omikron_psili;' => "\x{1f40}",
  '&Omikron_psili;' => "\x{1f48}",
  '&omikron_psili_acute;' => "\x{1f44}",
  '&Omikron_psili_acute;' => "\x{1f4c}",
  '&omikron_psili_grave;' => "\x{1f42}",
  '&Omikron_psili_grave;' => "\x{1f4a}",
  '&Omikron_ton;' => "\x{038c}",
  '&omikron_ton;' => "\x{03cc}",

  '&Pi;' => "\x{03a0}",
  '&pi;' => "\x{03c0}",

  '&Rho;' => "\x{03a1}",
  '&rho;' => "\x{03c1}",
  '&rho_densa;' => "\x{1fe5}",
  '&Rho_densa;' => "\x{1fec}",
  '&rho_psili;' => "\x{1fe4}",

  '&Sigma;' => "\x{03a3}",
  '&sigma;' => "\x{03c3}",
  '&sigma_fina;' => "\x{03c2}",

  '&Tau;' => "\x{03a4}",
  '&tau;' => "\x{03c4}",

  '&Ypsilon;' => "\x{03a5}",
  '&ypsilon;' => "\x{03c5}",
  '&ypsilon_acute;' => "\x{1f7b}",
  '&Ypsilon_acute;' => "\x{1feb}",
  '&ypsilon_breve;' => "\x{1fe0}",
  '&Ypsilon_breve;' => "\x{1fe8}",
  '&ypsilon_circ;' => "\x{1fe6}",
  '&ypsilon_densa;' => "\x{1f51}",
  '&Ypsilon_densa;' => "\x{1f59}",
  '&ypsilon_densa_acute;' => "\x{1f55}",
  '&Ypsilon_densa_acute;' => "\x{1f5d}",
  '&ypsilon_densa_circ;' => "\x{1f57}",
  '&Ypsilon_densa_circ;' => "\x{1f5f}",
  '&ypsilon_densa_grave;' => "\x{1f53}",
  '&Ypsilon_densa_grave;' => "\x{1f5b}",
  '&ypsilon_grave;' => "\x{1f7a}",
  '&Ypsilon_grave;' => "\x{1fea}",
  '&ypsilon_makron;' => "\x{1fe1}",
  '&Ypsilon_makron;' => "\x{1fe9}",
  '&ypsilon_psili;' => "\x{1f50}",
  '&ypsilon_psili_acute;' => "\x{1f54}",
  '&ypsilon_psili_circ;' => "\x{1f56}",
  '&ypsilon_psili_grave;' => "\x{1f52}",
  '&Ypsilon_ton;' => "\x{038e}",
  '&ypsilon_ton;' => "\x{03cd}",
  '&Ypsilon_trema;' => "\x{03ab}",
  '&ypsilon_trema;' => "\x{03cb}",
  '&ypsilon_trema_acute;' => "\x{1fe3}",
  '&ypsilon_trema_circ;' => "\x{1fe7}",
  '&ypsilon_trema_grave;' => "\x{1fe2}",
  '&ypsilon_trema_ton;' => "\x{03b0}",

  '&Phi;' => "\x{03a6}",
  '&phi;' => "\x{03c6}",
  '&Chi;' => "\x{03a7}",
  '&chi;' => "\x{03c7}",
  '&Psi;' => "\x{03a8}",
  '&psi;' => "\x{03c8}",

  '&Omega;' => "\x{03a9}",
  '&omega;' => "\x{03c9}",
  '&omega_acute;' => "\x{1f7d}",
  '&Omega_acute;' => "\x{1ffb}",
  '&omega_acute_subj;' => "\x{1ff4}",
  '&omega_circ;' => "\x{1ff6}",
  '&omega_circ_subj;' => "\x{1ff7}",
  '&omega_densa;' => "\x{1f61}",
  '&Omega_densa;' => "\x{1f69}",
  '&omega_densa_acute;' => "\x{1f65}",
  '&Omega_densa_acute;' => "\x{1f6d}",
  '&omega_densa_acute_subj;' => "\x{1fa5}",
  '&Omega_densa_acute_Subj;' => "\x{1fad}",
  '&omega_densa_circ;' => "\x{1f67}",
  '&Omega_densa_circ;' => "\x{1f6f}",
  '&omega_densa_circ_subj;' => "\x{1fa7}",
  '&Omega_densa_circ_Subj;' => "\x{1faf}",
  '&omega_densa_grave;' => "\x{1f63}",
  '&Omega_densa_grave;' => "\x{1f6b}",
  '&omega_densa_grave_subj;' => "\x{1fa3}",
  '&Omega_densa_grave_Subj;' => "\x{1fab}",
  '&omega_densa_subj;' => "\x{1fa1}",
  '&Omega_densa_Subj;' => "\x{1fa9}",
  '&omega_grave;' => "\x{1f7c}",
  '&Omega_grave;' => "\x{1ffa}",
  '&omega_grave_subj;' => "\x{1ff2}",
  '&omega_psili;' => "\x{1f60}",
  '&Omega_psili;' => "\x{1f68}",
  '&omega_psili_acute;' => "\x{1f64}",
  '&Omega_psili_acute;' => "\x{1f6c}",
  '&omega_psili_acute_subj;' => "\x{1fa4}",
  '&Omega_psili_acute_Subj;' => "\x{1fac}",
  '&omega_psili_circ;' => "\x{1f66}",
  '&Omega_psili_circ;' => "\x{1f6e}",
  '&omega_psili_circ_subj;' => "\x{1fa6}",
  '&Omega_psili_circ_Subj;' => "\x{1fae}",
  '&omega_psili_grave;' => "\x{1f62}",
  '&Omega_psili_grave;' => "\x{1f6a}",
  '&omega_psili_grave_subj;' => "\x{1fa2}",
  '&Omega_psili_grave_Subj;' => "\x{1faa}",
  '&omega_psili_subj;' => "\x{1fa0}",
  '&Omega_psili_Subj;' => "\x{1fa8}",
  '&omega_subj;' => "\x{1ff3}",
  '&Omega_Subj;' => "\x{1ffc}",
  '&Omega_ton;' => "\x{038f}",
  '&omega_ton;' => "\x{03ce}",

  # <!-- cirilaj -->
  '&c_Ju;' => "\x{042e}",
  '&c_A;' => "\x{0410}",
  '&c_B;' => "\x{0411}",
  '&c_C;' => "\x{0426}",
  '&c_D;' => "\x{0414}",
  '&c_Je;' => "\x{0415}",
  '&c_F;' => "\x{0424}",
  '&c_G;' => "\x{0413}",
  '&c_H;' => "\x{0425}",
  '&c_I;' => "\x{0418}",
  '&c_J;' => "\x{0419}",
  '&c_K;' => "\x{041a}",
  '&c_L;' => "\x{041b}",
  '&c_M;' => "\x{041c}",
  '&c_N;' => "\x{041d}",
  '&c_O;' => "\x{041e}",
  '&c_P;' => "\x{041f}",
  '&c_Ja;' => "\x{042f}",
  '&c_R;' => "\x{0420}",
  '&c_S;' => "\x{0421}",
  '&c_T;' => "\x{0422}",
  '&c_U;' => "\x{0423}",
  '&c_Zh;' => "\x{0416}",
  '&c_V;' => "\x{0412}",
  '&c_Mol;' => "\x{042c}",
  '&c_Y;' => "\x{042b}",
  '&c_Z;' => "\x{0417}",
  '&c_Sh;' => "\x{0428}",
  '&c_E;' => "\x{042d}",
  '&c_Shch;' => "\x{0429}",
  '&c_Ch;' => "\x{0427}",

  '&c_Jo;' => "\x{0401}",
  '&c_W;' => "\x{040E}",
  '&c_Ib;' => "\x{0406}",
  '&c_Gu;' => "\x{0490}",
  '&c_Jeu;' => "\x{0404}",
  '&c_Ji;' => "\x{0407}",

  '&c_ju;' => "\x{044e}",
  '&c_a;' => "\x{0430}",
  '&c_b;' => "\x{0431}",
  '&c_c;' => "\x{0446}",
  '&c_d;' => "\x{0434}",
  '&c_je;' => "\x{0435}",
  '&c_f;' => "\x{0444}",
  '&c_g;' => "\x{0433}",
  '&c_h;' => "\x{0445}",
  '&c_i;' => "\x{0438}",
  '&c_j;' => "\x{0439}",
  '&c_k;' => "\x{043a}",
  '&c_l;' => "\x{043b}",
  '&c_m;' => "\x{043c}",
  '&c_n;' => "\x{043d}",
  '&c_o;' => "\x{043e}",
  '&c_p;' => "\x{043f}",
  '&c_ja;' => "\x{044f}",
  '&c_r;' => "\x{0440}",
  '&c_s;' => "\x{0441}",
  '&c_t;' => "\x{0442}",
  '&c_u;' => "\x{0443}",
  '&c_zh;' => "\x{0436}",
  '&c_v;' => "\x{0432}",
  '&c_mol;' => "\x{044c}",
  '&c_y;' => "\x{044b}",
  '&c_z;' => "\x{0437}",
  '&c_sh;' => "\x{0448}",
  '&c_e;' => "\x{044d}",
  '&c_shch;' => "\x{0449}",
  '&c_ch;' => "\x{0447}",
  '&c_malmol;' => "\x{044a}",

  '&c_jo;' => "\x{0451}",
  '&c_w;' => "\x{045E}",
  '&c_ib;' => "\x{0456}",
  '&c_gu;' => "\x{0491}",
  '&c_jeu;' => "\x{0454}",
  '&c_ji;' => "\x{0457}",

  # <!-- chehhaj, slovakaj kaj polaj -->
  '&Ccaron;' => "\x{010c}",
  '&ccaron;' => "\x{010d}",
  '&Scaron;' => "\x{0160}",
  '&scaron;' => "\x{0161}",
  '&Rcaron;' => "\x{0158}",
  '&rcaron;' => "\x{0159}",
  '&Yacute;' => "\x{00dd}",
  '&yacute;' => "\x{00fd}",
  '&Zcaron;' => "\x{017d}",
  '&zcaron;' => "\x{017e}",
  '&Zdot;' => "\x{017b}",
  '&zdot;' => "\x{017c}",
  '&Ncaron;' => "\x{0147}",
  '&ncaron;' => "\x{0148}",
  '&Ecaron;' => "\x{011a}",
  '&ecaron;' => "\x{011b}",
  '&Dcaron;' => "\x{010e}",
  '&dcaron;' => "\x{010f}",
  '&Tcaron;' => "\x{0164}",
  '&tcaron;' => "\x{0165}",
  '&Uring ;' => "\x{016e}",
  '&uring ;' => "\x{016f}",

  '&Lacute;' => "\x{0139}",
  '&lacute;' => "\x{013a}",
  '&Lcaron;' => "\x{013d}",
  '&lcaron;' => "\x{013e}",
  '&Racute;' => "\x{0154}",
  '&racute;' => "\x{0155}",

  '&Aogonek;' => "\x{0104}",
  '&aogonek;' => "\x{0105}",
  '&Lstroke;' => "\x{0141}",
  '&lstroke;' => "\x{0142}",
  '&Eogonek;' => "\x{0118}",
  '&eogonek;' => "\x{0119}",
  '&Cacute;' => "\x{0106}",
  '&cacute;' => "\x{0107}",
  '&Nacute;' => "\x{0143}",
  '&nacute;' => "\x{0144}",
  '&Sacute;' => "\x{015a}",
  '&sacute;' => "\x{015b}",
  '&Zacute;' => "\x{0179}",
  '&zacute;' => "\x{017a}",

  '&alef;' => "\x{05d0}",
  '&bet;' => "\x{05d1}",
  '&gimel;' => "\x{05d2}",
  '&dalet;' => "\x{05d3}",
  '&he;' => "\x{05d4}",
  '&vav;' => "\x{05d5}",
  '&zayin;' => "\x{05d6}",
  '&het;' => "\x{05d7}",
  '&tet;' => "\x{05d8}",
  '&yod;' => "\x{05d9}",
  '&fkaf;' => "\x{05da}",
  '&kaf;' => "\x{05db}",
  '&lamed;' => "\x{05dc}",
  '&fmem;' => "\x{05dd}",
  '&mem;' => "\x{05de}",
  '&fnun;' => "\x{05df}",
  '&nun;' => "\x{05e0}",
  '&samekh;' => "\x{05e1}",
  '&ayin;' => "\x{05e2}",
  '&fpe;' => "\x{05e3}",
  '&pe;' => "\x{05e4}",
  '&ftsadi;' => "\x{05e5}",
  '&tsadi;' => "\x{05e6}",
  '&qof;' => "\x{05e7}",
  '&resh;' => "\x{05e8}",
  '&shin;' => "\x{05e9}",
  '&tav;' => "\x{05ea}",

  # <!-- hungaraj -->

#  # <!-- evitu, char shajne ne launormaj liternomoj -->
#  $str =~ s/\x{0150}/&Odacute;/g;
#  $str =~ s/\x{0151}/&odacute;/g;
#  $str =~ s/\x{0170}/&Udacute;/g;
#  $str =~ s/\x{0171}/&udacute;/g;

  # <!-- uzu tiujn anstataue -->
  '&Odblac;' => "\x{0150}",
  '&odblac;' => "\x{0151}",
  '&Udblac;' => "\x{0170}",
  '&udblac;' => "\x{0171}",

  # <!-- kimraj -->
  '&Ycirc;' => "\x{0176}",
  '&ycirc;' => "\x{0177}",
  '&Wgrave;' => "\x{1e80}",
  '&wgrave;' => "\x{1e81}",
  '&Wacute;' => "\x{1e82}",
  '&wacute;' => "\x{1e83}",
  '&Wuml;' => "\x{1e84}",
  '&wuml;' => "\x{1e85}",
  '&Ygrave;' => "\x{1ef2}",
  '&ygrave;' => "\x{1ef3}",
  '&Wcirc;' => "\x{0174}",
  '&wcirc;' => "\x{0175}",
  '&Yuml;' => "\x{0178}",
  '&yuml;' => "\x{00ff}",


  # <!-- arabaj/persaj -->
  '&a_komo;' => "\x{060C}",
  '&a_punktokomo;' => "\x{061B}",
  '&a_demando;' => "\x{061F}",
  '&a_hamza;' => "\x{0621}",
  '&a_A_madda;' => "\x{0622}",
  '&a_A_hamza_sure;' => "\x{0623}",
  '&a_w_hamza;' => "\x{0624}",
  '&a_A_hamza_sube;' => "\x{0625}",
  '&a_y_hamza;' => "\x{0626}",
  '&a_A;' => "\x{0627}",
  '&a_b;' => "\x{0628}",
  '&a_t_marbuta;' => "\x{0629}",
  '&a_t;' => "\x{062A}",
  '&a_th;' => "\x{062B}",
  '&a_j;' => "\x{062C}",
  '&a_H;' => "\x{062D}",
  '&a_kh;' => "\x{062E}",
  '&a_d;' => "\x{062F}",
  '&a_dh;' => "\x{0630}",
  '&a_r;' => "\x{0631}",
  '&a_z;' => "\x{0632}",
  '&a_s;' => "\x{0633}",
  '&a_sh;' => "\x{0634}",
  '&a_S;' => "\x{0635}",
  '&a_D;' => "\x{0636}",
  '&a_T;' => "\x{0637}",
  '&a_Z;' => "\x{0638}",
  '&a_ayn;' => "\x{0639}",
  '&a_gh;' => "\x{063A}",
  '&a_tatwil;' => "\x{0640}",
  '&a_f;' => "\x{0641}",
  '&a_q;' => "\x{0642}",
  '&a_k;' => "\x{0643}",
  '&a_l;' => "\x{0644}",
  '&a_m;' => "\x{0645}",
  '&a_n;' => "\x{0646}",
  '&a_h;' => "\x{0647}",
  '&a_w;' => "\x{0648}",
  '&a_A_maqsura;' => "\x{0649}",
  '&a_y;' => "\x{064A}",
  '&a_fathatan;' => "\x{064B}",
  '&a_dammatan;' => "\x{064C}",
  '&a_kasratan;' => "\x{064D}",
  '&a_fatha;' => "\x{064E}",
  '&a_damma;' => "\x{064F}",
  '&a_kasra;' => "\x{0650}",
  '&a_shadda;' => "\x{0651}",
  '&a_sukun;' => "\x{0652}",
  '&a_madda_sure;' => "\x{0653}",
  '&a_hamza_sure;' => "\x{0654}",
  '&a_hamza_sube;' => "\x{0655}",
  '&a_A_sube;' => "\x{0656}",
  '&a_0;' => "\x{0660}",
  '&a_1;' => "\x{0661}",
  '&a_2;' => "\x{0662}",
  '&a_3;' => "\x{0663}",
  '&a_4;' => "\x{0664}",
  '&a_5;' => "\x{0665}",
  '&a_6;' => "\x{0666}",
  '&a_7;' => "\x{0667}",
  '&a_8;' => "\x{0668}",
  '&a_9;' => "\x{0669}",
  '&a_procento;' => "\x{066A}",
  '&a_dekumakomo;' => "\x{066B}",
  '&a_milumakomo;' => "\x{066C}",
  '&a_asterisko;' => "\x{066D}",
  '&a_A_sure;' => "\x{0670}",
  '&a_A_wasla;' => "\x{0671}",
  '&f_p;' => "\x{067E}",
  '&f_ch;' => "\x{0686}",
  '&f_zh;' => "\x{0698}",
  '&f_k;' => "\x{06A9}",
  '&f_g;' => "\x{06AF}",
  '&u_hy;' => "\x{06C0}",
  '&f_y;' => "\x{06CC}",
  '&f_0;' => "\x{06F0}",
  '&f_1;' => "\x{06F1}",
  '&f_2;' => "\x{06F2}",
  '&f_3;' => "\x{06F3}",
  '&f_4;' => "\x{06F4}",
  '&f_5;' => "\x{06F5}",
  '&f_6;' => "\x{06F6}",
  '&f_7;' => "\x{06F7}",
  '&f_8;' => "\x{06F8}",
  '&f_9;' => "\x{06F9}",
  '&a_fatha_A;' => "\x{064E}\x{0627}",
  '&a_kasra_y;' => "\x{0650}\x{064A}",
  '&a_damma_w;' => "\x{064F}\x{0648}",

  # <!-- formatsignoj -->
  '&zwnj;' => "\x{200C}",
  '&zwj;' => "\x{200D}",
  '&lrm;' => "\x{200E}",
  '&rlm;' => "\x{200F}",
  '&lre;' => "\x{202A}",
  '&rle;' => "\x{202B}",
  '&pdf;' => "\x{202C}",
  '&lro;' => "\x{202D}",
  '&rlo;' => "\x{202E}",

  # <!-- subteno por malnovaj arabaj nomoj -->
  '&ar_komo;' => "\x{060C}",
  '&ar_punktokomo;' => "\x{061B}",
  '&ar_demandopunkto;' => "\x{061F}",
  '&hamza;' => "\x{0621}",
  '&alif_madda;' => "\x{0622}",
  '&alif_hamza_sure;' => "\x{0623}",
  '&waw_hamza;' => "\x{0624}",
  '&alif_hamza_sube;' => "\x{0625}",
  '&ya_hamza;' => "\x{0626}",
  '&alif;' => "\x{0627}",
  '&ba;' => "\x{0628}",
  '&ta_marbuta;' => "\x{0629}",
  '&ta;' => "\x{062A}",
  '&tha;' => "\x{062B}",
  '&jim;' => "\x{062C}",
  '&Ha;' => "\x{062D}",
  '&hha;' => "\x{062E}",
  '&dal;' => "\x{062F}",
  '&dhal;' => "\x{0630}",
  '&ra;' => "\x{0631}",
  '&zin;' => "\x{0632}",
  '&sin;' => "\x{0633}",
  '&shin1;' => "\x{0634}",
  '&Sad;' => "\x{0635}",
  '&Dad;' => "\x{0636}",
  '&Ta;' => "\x{0637}",
  '&Za;' => "\x{0638}",
  '&ayn;' => "\x{0639}",
  '&ghayn;' => "\x{063A}",
  '&fa;' => "\x{0641}",
  '&qaf;' => "\x{0642}",
  '&kaf1;' => "\x{0643}",
  '&lam;' => "\x{0644}",
  '&mim;' => "\x{0645}",
  '&nun1;' => "\x{0646}",
  '&ha;' => "\x{0647}",
  '&waw;' => "\x{0648}",
  '&alif_maqsura;' => "\x{0649}",
  '&ya;' => "\x{064A}",
  '&fathatan;' => "\x{064B}",
  '&dammatan;' => "\x{064C}",
  '&kasratan;' => "\x{064D}",
  '&fatha;' => "\x{064E}",
  '&damma;' => "\x{064F}",
  '&kasra;' => "\x{0650}",
  '&shadda;' => "\x{0651}",
  '&sukun;' => "\x{0652}",
  '&ar_0;' => "\x{0660}",
  '&ar_1;' => "\x{0661}",
  '&ar_2;' => "\x{0662}",
  '&ar_3;' => "\x{0663}",
  '&ar_4;' => "\x{0664}",
  '&ar_5;' => "\x{0665}",
  '&ar_6;' => "\x{0666}",
  '&ar_7;' => "\x{0667}",
  '&ar_8;' => "\x{0668}",
  '&ar_9;' => "\x{0669}",
  '&ar_dekumakomo;' => "\x{066B}",
  '&alif_wasla;' => "\x{0671}",
  '&fatha_alif;' => "\x{064E}\x{0627}",
  '&kasra_ya;' => "\x{0650}\x{064A}",
  '&damma_waw;' => "\x{064F}\x{0648}",

  # <!-- subteno por malnovaj persaj nomoj -->
  '&fa_komo;' => "\x{060C}",
  '&fa_punktokomo;' => "\x{061B}",
  '&fa_demando;' => "\x{061F}",
  '&fa_hamze;' => "\x{0621}",
  '&fa_a;' => "\x{0622}",
  '&fa_hamze_a;' => "\x{0623}",
  '&fa_hamze_u;' => "\x{0624}",
  '&fa_hamze_e;' => "\x{0625}",
  '&fa_hamze_i;' => "\x{0626}",
  '&fa_alef;' => "\x{0627}",
  '&fa_be;' => "\x{0628}",
  '&fa_te_marbute;' => "\x{0629}",
  '&fa_te;' => "\x{062A}",
  '&fa_se;' => "\x{062B}",
  '&fa_gxim;' => "\x{062C}",
  '&fa_he;' => "\x{062D}",
  '&fa_hxe;' => "\x{062E}",
  '&fa_dal;' => "\x{062F}",
  '&fa_zal;' => "\x{0630}",
  '&fa_re;' => "\x{0631}",
  '&fa_ze;' => "\x{0632}",
  '&fa_sin;' => "\x{0633}",
  '&fa_sxin;' => "\x{0634}",
  '&fa_sat;' => "\x{0635}",
  '&fa_zat;' => "\x{0636}",
  '&fa_ta;' => "\x{0637}",
  '&fa_za;' => "\x{0638}",
  '&fa_ein;' => "\x{0639}",
  '&fa_qein;' => "\x{063A}",
  '&fa_fe;' => "\x{0641}",
  '&fa_qaf;' => "\x{0642}",
  '&fa_lam;' => "\x{0644}",
  '&fa_mim;' => "\x{0645}",
  '&fa_nun;' => "\x{0646}",
  '&fa_heh;' => "\x{0647}",
  '&fa_vav;' => "\x{0648}",
  '&fa_fathatan;' => "\x{064B}",
  '&fa_zammatan;' => "\x{064C}",
  '&fa_kasratan;' => "\x{064D}",
  '&fa_fathe;' => "\x{064E}",
  '&fa_zamme;' => "\x{064F}",
  '&fa_kasre;' => "\x{0650}",
  '&fa_tasxdid;' => "\x{0651}",
  '&fa_sokun;' => "\x{0652}",
  '&fa_madde_sur;' => "\x{0653}",
  '&fa_hamze_sur;' => "\x{0654}",
  '&fa_hamze_sub;' => "\x{0655}",
  '&fa_pe;' => "\x{067E}",
  '&fa_cxe;' => "\x{0686}",
  '&fa_jxe;' => "\x{0698}",
  '&fa_kaf;' => "\x{06A9}",
  '&fa_gaf;' => "\x{06AF}",
  '&fa_heh_ezafe;' => "\x{06C0}",
  '&fa_ye;' => "\x{06CC}",
  '&fa_0;' => "\x{06F0}",
  '&fa_1;' => "\x{06F1}",
  '&fa_2;' => "\x{06F2}",
  '&fa_3;' => "\x{06F3}",
  '&fa_4;' => "\x{06F4}",
  '&fa_5;' => "\x{06F5}",
  '&fa_6;' => "\x{06F6}",
  '&fa_7;' => "\x{06F7}",
  '&fa_8;' => "\x{06F8}",
  '&fa_9;' => "\x{06F9}",
  '&fa_zwnj;' => "\x{200C}",
  '&fa_zwj;' => "\x{200D}",

  '&amp;' => '&'
  );

  my $regex = join '|', map { quotemeta } keys %map;
  $str =~ s{($regex)}{$map{$1}}xg;

  ## no critic (Variables::ProhibitPackageVars)
  delete $HTML::Entities::entity2char{quot};
  delete $HTML::Entities::entity2char{lt};
  delete $HTML::Entities::entity2char{gt};
  ## use critic
  $str = HTML::Entities::decode_entities($str);
#  print "encode -> ".Encode::encode($enc, $str)."\n";
  return Encode::encode($enc, $str);
}
    
######################################################################

1;

