#!/usr/bin/perl
package revo::encode;

#
# revo::encode.pm
# 
# 2008-02-09 Wieland Pusch
# ..2026 Wolfram Diestel

use warnings; use strict;


use utf8;
use Encode;
use HTML::Entities;
use CGI qw(:standard);  # nur por verbose

######################################################################

{
  ## no critic (TestingAndDebugging::ProhibitNoWarnings)
  no warnings 'redefine';
  ## no critic (Subroutines::ProhibitSubroutinePrototypes)
  sub encode($$;$) {
    my ($str, $verbose) = @_;
    return encode2($str, 0, $verbose);
  }
  ## use critic
}
######################################################################
sub encode2 {
  my ($str, $flag, $verbose) = @_;
  my $enc = "utf-8";
  # print pre("encode2") if $verbose;
  $str = Encode::decode($enc, $str) unless Encode::is_utf8($str);

  # print pre(escapeHTML("encode ".Encode::encode($enc, $str)))."\n" if $verbose;

  ## no critic (RegularExpressions::RequireExtendedFormatting)
  $str =~ s/&(?![#a-zA-Z0-9_]+;)/&amp;/g;
  # <!-- diversaj -->
  $str =~ s/</&lt;/g if $flag < 10;
  $str =~ s/>/&gt;/g if $flag < 10;
#  $str =~ s/'/&apos;/g;
#  $str =~ s/'/&minute;/g;
  $str =~ s/"/&quot;/g if $flag < 10;
  ## use critic

  my %map = (  
  # <!-- e-aj literoj -->
  "\x{0108}" => '&Ccirc;',
  "\x{0109}" => '&ccirc;',
  "\x{011c}" => '&Gcirc;',
  "\x{011d}" => '&gcirc;',
  "\x{0124}" => '&Hcirc;',
  "\x{0125}" => '&hcirc;',
  "\x{0134}" => '&Jcirc;',
  "\x{0135}" => '&jcirc;',
  "\x{015c}" => '&Scirc;',
  "\x{015d}" => '&scirc;',
  "\x{016c}" => '&Ubreve;',
  "\x{016d}" => '&ubreve;',

  # <!-- francaj k.a. -->
  "\x{0152}" => '&OElig;',
  "\x{0153}" => '&oelig;',
  "\x{00c1}" => '&Aacute;',
  "\x{00e1}" => '&aacute;',
  "\x{00c9}" => '&Eacute;',
  "\x{00e9}" => '&eacute;',
  "\x{00cd}" => '&Iacute;',
  "\x{00ed}" => '&iacute;',
  "\x{00d3}" => '&Oacute;',
  "\x{00f3}" => '&oacute;',
  "\x{00da}" => '&Uacute;',
  "\x{00fa}" => '&uacute;',

  "\x{00c0}" => '&Agrave;',
  "\x{00e0}" => '&agrave;',
  "\x{00c8}" => '&Egrave;',
  "\x{00e8}" => '&egrave;',
  "\x{00cc}" => '&Igrave;',
  "\x{00ec}" => '&igrave;',
  "\x{00d2}" => '&Ograve;',
  "\x{00f2}" => '&ograve;',
  "\x{00d9}" => '&Ugrave;',
  "\x{00f9}" => '&ugrave;',

  "\x{00c2}" => '&Acirc;',
  "\x{00e2}" => '&acirc;',
  "\x{00ca}" => '&Ecirc;',
  "\x{00ea}" => '&ecirc;',
  "\x{00ce}" => '&Icirc;',
  "\x{00ee}" => '&icirc;',
  "\x{00d4}" => '&Ocirc;',
  "\x{00f4}" => '&ocirc;',
  "\x{00db}" => '&Ucirc;',
  "\x{00fb}" => '&ucirc;',

  # <!-- germanaj -->
  "\x{00df}" => '&szlig;',
  "\x{00c4}" => '&Auml;',
  "\x{00e4}" => '&auml;',
  "\x{00d6}" => '&Ouml;',
  "\x{00f6}" => '&ouml;',
  "\x{00dc}" => '&Uuml;',
  "\x{00fc}" => '&uuml;',

  # <!-- turkaj ne jam menciitaj -->
  "\x{011e}" => '&Gbreve;',
  "\x{011f}" => '&gbreve;',
  "\x{0131}" => '&inodot;',
  "\x{0130}" => '&Idot;',
  "\x{015e}" => '&Scedil;',
  "\x{015f}" => '&scedil;',
  "\x{00c7}" => '&Ccedil;',
  "\x{00e7}" => '&ccedil;',

#  "\x{0034}" => '&second',
  "\x{201e}" => '&leftquot;',
  "\x{201c}" => '&rightquot;',
#  "\x{00b0}" => '&ring;',
  "\x{00b0}" => '&deg;',
  "\x{00b2}" => '&quadrat;',
  "\x{00b3}" => '&cubic;',
  "\x{00B6}" => '&para;',
#  "\x{00a7}" => '&FE;',
  "\x{2015}" => '&dash;',
  "\x{2014}" => '&mdash;',
  "\x{2013}" => '&ndash;',
  "\x{00a0}" => '&nbsp;',

  "\x{00cb}" => '&Euml;',
  "\x{00eb}" => '&euml;',
  "\x{00cf}" => '&Iuml;',
  "\x{00ef}" => '&iuml;',

  "\x{00c5}" => '&Aring;',
  "\x{00e5}" => '&aring;',
  "\x{00c6}" => '&AElig;',
  "\x{00e6}" => '&aelig;',
  "\x{00d8}" => '&Oslash;',
  "\x{00f8}" => '&oslash;',

  # <!-- portugalaj, hispanaj, katalunaj -->
  "\x{00d1}" => '&Ntilde;',
  "\x{00f1}" => '&ntilde;',

  "\x{00c3}" => '&Atilde;',
  "\x{00e3}" => '&atilde;',
  "\x{00d5}" => '&Otilde;',
  "\x{00f5}" => '&otilde;',

  "\x{00b7}" => '&middot;',

  # <!-- rumanaj -->
  "\x{0102}" => '&Abreve;',
  "\x{0103}" => '&abreve;',
  "\x{0162}" => '&Tcedil;',
  "\x{0163}" => '&tcedil;',

  # <!-- grekaj -->
  "\x{0391}" => '&Alfa;',
  "\x{03b1}" => '&alfa;',
  "\x{1f71}" => '&alfa_acute;',
  "\x{1fbb}" => '&Alfa_acute;',
  "\x{1fb4}" => '&alfa_acute_subj;',
  "\x{1fb0}" => '&alfa_breve;',
  "\x{1fb8}" => '&Alfa_breve;',
  "\x{1fb6}" => '&alfa_circ;',
  "\x{1fb7}" => '&alfa_circ_subj;',
  "\x{1f01}" => '&alfa_densa;',
  "\x{1f09}" => '&Alfa_densa;',
  "\x{1f05}" => '&alfa_densa_acute;',
  "\x{1f0d}" => '&Alfa_densa_acute;',
  "\x{1f85}" => '&alfa_densa_acute_subj;',
  "\x{1f8d}" => '&Alfa_densa_acute_Subj;',
  "\x{1f07}" => '&alfa_densa_circ;',
  "\x{1f0f}" => '&Alfa_densa_circ;',
  "\x{1f87}" => '&alfa_densa_circ_subj;',
  "\x{1f8f}" => '&Alfa_densa_circ_Subj;',
  "\x{1f03}" => '&alfa_densa_grave;',
  "\x{1f0b}" => '&Alfa_densa_grave;',
  "\x{1f83}" => '&alfa_densa_grave_subj;',
  "\x{1f8b}" => '&Alfa_densa_grave_Subj;',
  "\x{1f81}" => '&alfa_densa_subj;',
  "\x{1f89}" => '&Alfa_densa_Subj;',
  "\x{1f70}" => '&alfa_grave;',
  "\x{1fba}" => '&Alfa_grave;',
  "\x{1fb2}" => '&alfa_grave_subj;',
  "\x{1fb1}" => '&alfa_makron;',
  "\x{1fb9}" => '&Alfa_makron;',
  "\x{1f00}" => '&alfa_psili;',
  "\x{1f08}" => '&Alfa_psili;',
  "\x{1f04}" => '&alfa_psili_acute;',
  "\x{1f0c}" => '&Alfa_psili_acute;',
  "\x{1f84}" => '&alfa_psili_acute_subj;',
  "\x{1f8c}" => '&Alfa_psili_acute_Subj;',
  "\x{1f06}" => '&alfa_psili_circ;',
  "\x{1f0e}" => '&Alfa_psili_circ;',
  "\x{1f86}" => '&alfa_psili_circ_subj;',
  "\x{1f8e}" => '&Alfa_psili_circ_Subj;',
  "\x{1f02}" => '&alfa_psili_grave;',
  "\x{1f0a}" => '&Alfa_psili_grave;',
  "\x{1f82}" => '&alfa_psili_grave_subj;',
  "\x{1f8a}" => '&Alfa_psili_grave_Subj;',
  "\x{1f80}" => '&alfa_psili_subj;',
  "\x{1f88}" => '&Alfa_psili_Subj;',
  "\x{1fb3}" => '&alfa_subj;',
  "\x{1fbc}" => '&Alfa_Subj;',
  "\x{0386}" => '&Alfa_ton;',
  "\x{03ac}" => '&alfa_ton;',

  "\x{0392}" => '&Beta;',
  "\x{03b2}" => '&beta;',

  "\x{0393}" => '&Gamma;',
  "\x{03b3}" => '&gamma;',

  "\x{0394}" => '&Delta;',
  "\x{03b4}" => '&delta;',

  "\x{0395}" => '&Epsilon;',
  "\x{03b5}" => '&epsilon;',
  "\x{1f73}" => '&epsilon_acute;',
  "\x{1fc9}" => '&Epsilon_acute;',
  "\x{1f11}" => '&epsilon_densa;',
  "\x{1f19}" => '&Epsilon_densa;',
  "\x{1f15}" => '&epsilon_densa_acute;',
  "\x{1f1d}" => '&Epsilon_densa_acute;',
  "\x{1f13}" => '&epsilon_densa_grave;',
  "\x{1f1b}" => '&Epsilon_densa_grave;',
  "\x{1f72}" => '&epsilon_grave;',
  "\x{1fc8}" => '&Epsilon_grave;',
  "\x{1f10}" => '&epsilon_psili;',
  "\x{1f18}" => '&Epsilon_psili;',
  "\x{1f14}" => '&epsilon_psili_acute;',
  "\x{1f1c}" => '&Epsilon_psili_acute;',
  "\x{1f12}" => '&epsilon_psili_grave;',
  "\x{1f1a}" => '&Epsilon_psili_grave;',
  "\x{0388}" => '&Epsilon_ton;',
  "\x{03ad}" => '&epsilon_ton;',

  "\x{0396}" => '&Zeta;',
  "\x{03b6}" => '&zeta;',

  "\x{0397}" => '&Eta;',
  "\x{03b7}" => '&eta;',
  "\x{1f75}" => '&eta_acute;',
  "\x{1fcb}" => '&Eta_acute;',
  "\x{1fc4}" => '&eta_acute_subj;',
  "\x{1fc6}" => '&eta_circ;',
  "\x{1fc7}" => '&eta_circ_subj;',
  "\x{1f21}" => '&eta_densa;',
  "\x{1f29}" => '&Eta_densa;',
  "\x{1f25}" => '&eta_densa_acute;',
  "\x{1f2d}" => '&Eta_densa_acute;',
  "\x{1f95}" => '&eta_densa_acute_subj;',
  "\x{1f9d}" => '&Eta_densa_acute_Subj;',
  "\x{1f27}" => '&eta_densa_circ;',
  "\x{1f2f}" => '&Eta_densa_circ;',
  "\x{1f97}" => '&eta_densa_circ_subj;',
  "\x{1f9f}" => '&Eta_densa_circ_Subj;',
  "\x{1f23}" => '&eta_densa_grave;',
  "\x{1f2b}" => '&Eta_densa_grave;',
  "\x{1f93}" => '&eta_densa_grave_subj;',
  "\x{1f9b}" => '&Eta_densa_grave_Subj;',
  "\x{1f91}" => '&eta_densa_subj;',
  "\x{1f99}" => '&Eta_densa_Subj;',
  "\x{1f74}" => '&eta_grave;',
  "\x{1fca}" => '&Eta_grave;',
  "\x{1fc2}" => '&eta_grave_subj;',
  "\x{1f20}" => '&eta_psili;',
  "\x{1f28}" => '&Eta_psili;',
  "\x{1f24}" => '&eta_psili_acute;',
  "\x{1f2c}" => '&Eta_psili_acute;',
  "\x{1f94}" => '&eta_psili_acute_subj;',
  "\x{1f9c}" => '&Eta_psili_acute_Subj;',
  "\x{1f26}" => '&eta_psili_circ;',
  "\x{1f2e}" => '&Eta_psili_circ;',
  "\x{1f96}" => '&eta_psili_circ_subj;',
  "\x{1f9e}" => '&Eta_psili_circ_Subj;',
  "\x{1f22}" => '&eta_psili_grave;',
  "\x{1f2a}" => '&Eta_psili_grave;',
  "\x{1f92}" => '&eta_psili_grave_subj;',
  "\x{1f9a}" => '&Eta_psili_grave_Subj;',
  "\x{1f90}" => '&eta_psili_subj;',
  "\x{1f98}" => '&Eta_psili_Subj;',
  "\x{1fc3}" => '&eta_subj;',
  "\x{1fcc}" => '&Eta_Subj;',
  "\x{0389}" => '&Eta_ton;',
  "\x{03ae}" => '&eta_ton;',

  "\x{0398}" => '&Theta;',
  "\x{03b8}" => '&theta;',

  "\x{0399}" => '&Jota;',
  "\x{03b9}" => '&jota;',
  "\x{1f77}" => '&jota_acute;',
  "\x{1fdb}" => '&Jota_acute;',
  "\x{1fd0}" => '&jota_breve;',
  "\x{1fd8}" => '&Jota_breve;',
  "\x{1fd6}" => '&jota_circ;',
  "\x{1f31}" => '&jota_densa;',
  "\x{1f39}" => '&Jota_densa;',
  "\x{1f35}" => '&jota_densa_acute;',
  "\x{1f3d}" => '&Jota_densa_acute;',
  "\x{1f37}" => '&jota_densa_circ;',
  "\x{1f3f}" => '&Jota_densa_circ;',
  "\x{1f33}" => '&jota_densa_grave;',
  "\x{1f3b}" => '&Jota_densa_grave;',
  "\x{1f76}" => '&jota_grave;',
  "\x{1fda}" => '&Jota_grave;',
  "\x{1fd1}" => '&jota_makron;',
  "\x{1fd9}" => '&Jota_makron;',
  "\x{1f30}" => '&jota_psili;',
  "\x{1f38}" => '&Jota_psili;',
  "\x{1f34}" => '&jota_psili_acute;',
  "\x{1f3c}" => '&Jota_psili_acute;',
  "\x{1f36}" => '&jota_psili_circ;',
  "\x{1f3e}" => '&Jota_psili_circ;',
  "\x{1f32}" => '&jota_psili_grave;',
  "\x{1f3a}" => '&Jota_psili_grave;',
  "\x{038a}" => '&Jota_ton;',
  "\x{03af}" => '&jota_ton;',
  "\x{03aa}" => '&Jota_trema;',
  "\x{03ca}" => '&jota_trema;',
  "\x{1fd3}" => '&jota_trema_acute;',
  "\x{1fd7}" => '&jota_trema_circ;',
  "\x{1fd2}" => '&jota_trema_grave;',
  "\x{0390}" => '&jota_trema_ton;',

  "\x{039a}" => '&Kappa;',
  "\x{03ba}" => '&kappa;',
  "\x{039b}" => '&Lambda;',
  "\x{03bb}" => '&lambda;',
  "\x{039c}" => '&My;',
  "\x{03bc}" => '&my;',
  "\x{039d}" => '&Ny;',
  "\x{03bd}" => '&ny;',
  "\x{039e}" => '&Xi;',
  "\x{03be}" => '&xi;',

  "\x{039f}" => '&Omikron;',
  "\x{03bf}" => '&omikron;',
  "\x{1f79}" => '&omikron_acute;',
  "\x{1ff9}" => '&Omikron_acute;',
  "\x{1f41}" => '&omikron_densa;',
  "\x{1f49}" => '&Omikron_densa;',
  "\x{1f45}" => '&omikron_densa_acute;',
  "\x{1f4d}" => '&Omikron_densa_acute;',
  "\x{1f43}" => '&omikron_densa_grave;',
  "\x{1f4b}" => '&Omikron_densa_grave;',
  "\x{1f78}" => '&omikron_grave;',
  "\x{1ff8}" => '&Omikron_grave;',
  "\x{1f40}" => '&omikron_psili;',
  "\x{1f48}" => '&Omikron_psili;',
  "\x{1f44}" => '&omikron_psili_acute;',
  "\x{1f4c}" => '&Omikron_psili_acute;',
  "\x{1f42}" => '&omikron_psili_grave;',
  "\x{1f4a}" => '&Omikron_psili_grave;',
  "\x{038c}" => '&Omikron_ton;',
  "\x{03cc}" => '&omikron_ton;',

  "\x{03a0}" => '&Pi;',
  "\x{03c0}" => '&pi;',

  "\x{03a1}" => '&Rho;',
  "\x{03c1}" => '&rho;',
  "\x{1fe5}" => '&rho_densa;',
  "\x{1fec}" => '&Rho_densa;',
  "\x{1fe4}" => '&rho_psili;',

  "\x{03a3}" => '&Sigma;',
  "\x{03c3}" => '&sigma;',
  "\x{03c2}" => '&sigma_fina;',

  "\x{03a4}" => '&Tau;',
  "\x{03c4}" => '&tau;',

  "\x{03a5}" => '&Ypsilon;',
  "\x{03c5}" => '&ypsilon;',
  "\x{1f7b}" => '&ypsilon_acute;',
  "\x{1feb}" => '&Ypsilon_acute;',
  "\x{1fe0}" => '&ypsilon_breve;',
  "\x{1fe8}" => '&Ypsilon_breve;',
  "\x{1fe6}" => '&ypsilon_circ;',
  "\x{1f51}" => '&ypsilon_densa;',
  "\x{1f59}" => '&Ypsilon_densa;',
  "\x{1f55}" => '&ypsilon_densa_acute;',
  "\x{1f5d}" => '&Ypsilon_densa_acute;',
  "\x{1f57}" => '&ypsilon_densa_circ;',
  "\x{1f5f}" => '&Ypsilon_densa_circ;',
  "\x{1f53}" => '&ypsilon_densa_grave;',
  "\x{1f5b}" => '&Ypsilon_densa_grave;',
  "\x{1f7a}" => '&ypsilon_grave;',
  "\x{1fea}" => '&Ypsilon_grave;',
  "\x{1fe1}" => '&ypsilon_makron;',
  "\x{1fe9}" => '&Ypsilon_makron;',
  "\x{1f50}" => '&ypsilon_psili;',
  "\x{1f54}" => '&ypsilon_psili_acute;',
  "\x{1f56}" => '&ypsilon_psili_circ;',
  "\x{1f52}" => '&ypsilon_psili_grave;',
  "\x{038e}" => '&Ypsilon_ton;',
  "\x{03cd}" => '&ypsilon_ton;',
  "\x{03ab}" => '&Ypsilon_trema;',
  "\x{03cb}" => '&ypsilon_trema;',
  "\x{1fe3}" => '&ypsilon_trema_acute;',
  "\x{1fe7}" => '&ypsilon_trema_circ;',
  "\x{1fe2}" => '&ypsilon_trema_grave;',
  "\x{03b0}" => '&ypsilon_trema_ton;',

  "\x{03a6}" => '&Phi;',
  "\x{03c6}" => '&phi;',
  "\x{03a7}" => '&Chi;',
  "\x{03c7}" => '&chi;',
  "\x{03a8}" => '&Psi;',
  "\x{03c8}" => '&psi;',

  "\x{03a9}" => '&Omega;',
  "\x{03c9}" => '&omega;',
  "\x{1f7d}" => '&omega_acute;',
  "\x{1ffb}" => '&Omega_acute;',
  "\x{1ff4}" => '&omega_acute_subj;',
  "\x{1ff6}" => '&omega_circ;',
  "\x{1ff7}" => '&omega_circ_subj;',
  "\x{1f61}" => '&omega_densa;',
  "\x{1f69}" => '&Omega_densa;',
  "\x{1f65}" => '&omega_densa_acute;',
  "\x{1f6d}" => '&Omega_densa_acute;',
  "\x{1fa5}" => '&omega_densa_acute_subj;',
  "\x{1fad}" => '&Omega_densa_acute_Subj;',
  "\x{1f67}" => '&omega_densa_circ;',
  "\x{1f6f}" => '&Omega_densa_circ;',
  "\x{1fa7}" => '&omega_densa_circ_subj;',
  "\x{1faf}" => '&Omega_densa_circ_Subj;',
  "\x{1f63}" => '&omega_densa_grave;',
  "\x{1f6b}" => '&Omega_densa_grave;',
  "\x{1fa3}" => '&omega_densa_grave_subj;',
  "\x{1fab}" => '&Omega_densa_grave_Subj;',
  "\x{1fa1}" => '&omega_densa_subj;',
  "\x{1fa9}" => '&Omega_densa_Subj;',
  "\x{1f7c}" => '&omega_grave;',
  "\x{1ffa}" => '&Omega_grave;',
  "\x{1ff2}" => '&omega_grave_subj;',
  "\x{1f60}" => '&omega_psili;',
  "\x{1f68}" => '&Omega_psili;',
  "\x{1f64}" => '&omega_psili_acute;',
  "\x{1f6c}" => '&Omega_psili_acute;',
  "\x{1fa4}" => '&omega_psili_acute_subj;',
  "\x{1fac}" => '&Omega_psili_acute_Subj;',
  "\x{1f66}" => '&omega_psili_circ;',
  "\x{1f6e}" => '&Omega_psili_circ;',
  "\x{1fa6}" => '&omega_psili_circ_subj;',
  "\x{1fae}" => '&Omega_psili_circ_Subj;',
  "\x{1f62}" => '&omega_psili_grave;',
  "\x{1f6a}" => '&Omega_psili_grave;',
  "\x{1fa2}" => '&omega_psili_grave_subj;',
  "\x{1faa}" => '&Omega_psili_grave_Subj;',
  "\x{1fa0}" => '&omega_psili_subj;',
  "\x{1fa8}" => '&Omega_psili_Subj;',
  "\x{1ff3}" => '&omega_subj;',
  "\x{1ffc}" => '&Omega_Subj;',
  "\x{038f}" => '&Omega_ton;',
  "\x{03ce}" => '&omega_ton;',

  # <!-- cirilaj -->
  "\x{042e}" => '&c_Ju;',
  "\x{0410}" => '&c_A;',
  "\x{0411}" => '&c_B;',
  "\x{0426}" => '&c_C;',
  "\x{0414}" => '&c_D;',
  "\x{0415}" => '&c_Je;',
  "\x{0424}" => '&c_F;',
  "\x{0413}" => '&c_G;',
  "\x{0425}" => '&c_H;',
  "\x{0418}" => '&c_I;',
  "\x{0419}" => '&c_J;',
  "\x{041a}" => '&c_K;',
  "\x{041b}" => '&c_L;',
  "\x{041c}" => '&c_M;',
  "\x{041d}" => '&c_N;',
  "\x{041e}" => '&c_O;',
  "\x{041f}" => '&c_P;',
  "\x{042f}" => '&c_Ja;',
  "\x{0420}" => '&c_R;',
  "\x{0421}" => '&c_S;',
  "\x{0422}" => '&c_T;',
  "\x{0423}" => '&c_U;',
  "\x{0416}" => '&c_Zh;',
  "\x{0412}" => '&c_V;',
  "\x{042c}" => '&c_Mol;',
  "\x{042b}" => '&c_Y;',
  "\x{0417}" => '&c_Z;',
  "\x{0428}" => '&c_Sh;',
  "\x{042d}" => '&c_E;',
  "\x{0429}" => '&c_Shch;',
  "\x{0427}" => '&c_Ch;',

  "\x{0401}" => '&c_Jo;',
  "\x{040E}" => '&c_W;',
  "\x{0406}" => '&c_Ib;',
  "\x{0490}" => '&c_Gu;',
  "\x{0404}" => '&c_Jeu;',
  "\x{0407}" => '&c_Ji;',

  "\x{044e}" => '&c_ju;',
  "\x{0430}" => '&c_a;',
  "\x{0431}" => '&c_b;',
  "\x{0446}" => '&c_c;',
  "\x{0434}" => '&c_d;',
  "\x{0435}" => '&c_je;',
  "\x{0444}" => '&c_f;',
  "\x{0433}" => '&c_g;',
  "\x{0445}" => '&c_h;',
  "\x{0438}" => '&c_i;',
  "\x{0439}" => '&c_j;',
  "\x{043a}" => '&c_k;',
  "\x{043b}" => '&c_l;',
  "\x{043c}" => '&c_m;',
  "\x{043d}" => '&c_n;',
  "\x{043e}" => '&c_o;',
  "\x{043f}" => '&c_p;',
  "\x{044f}" => '&c_ja;',
  "\x{0440}" => '&c_r;',
  "\x{0441}" => '&c_s;',
  "\x{0442}" => '&c_t;',
  "\x{0443}" => '&c_u;',
  "\x{0436}" => '&c_zh;',
  "\x{0432}" => '&c_v;',
  "\x{044c}" => '&c_mol;',
  "\x{044b}" => '&c_y;',
  "\x{0437}" => '&c_z;',
  "\x{0448}" => '&c_sh;',
  "\x{044d}" => '&c_e;',
  "\x{0449}" => '&c_shch;',
  "\x{0447}" => '&c_ch;',
  "\x{044a}" => '&c_malmol;',

  "\x{0451}" => '&c_jo;',
  "\x{045E}" => '&c_w;',
  "\x{0456}" => '&c_ib;',
  "\x{0491}" => '&c_gu;',
  "\x{0454}" => '&c_jeu;',
  "\x{0457}" => '&c_ji;',

  # <!-- chehhaj, slovakaj kaj polaj -->
  "\x{010c}" => '&Ccaron;',
  "\x{010d}" => '&ccaron;',
  "\x{0160}" => '&Scaron;',
  "\x{0161}" => '&scaron;',
  "\x{0158}" => '&Rcaron;',
  "\x{0159}" => '&rcaron;',
  "\x{00dd}" => '&Yacute;',
  "\x{00fd}" => '&yacute;',
  "\x{017d}" => '&Zcaron;',
  "\x{017e}" => '&zcaron;',
  "\x{017b}" => '&Zdot;',
  "\x{017c}" => '&zdot;',
  "\x{0147}" => '&Ncaron;',
  "\x{0148}" => '&ncaron;',
  "\x{011a}" => '&Ecaron;',
  "\x{011b}" => '&ecaron;',
  "\x{010e}" => '&Dcaron;',
  "\x{010f}" => '&dcaron;',
  "\x{0164}" => '&Tcaron;',
  "\x{0165}" => '&tcaron;',
  "\x{016e}" => '&Uring;',
  "\x{016f}" => '&uring;',

  "\x{0139}" => '&Lacute;',
  "\x{013a}" => '&lacute;',
  "\x{013d}" => '&Lcaron;',
  "\x{013e}" => '&lcaron;',
  "\x{0154}" => '&Racute;',
  "\x{0155}" => '&racute;',

  "\x{0104}" => '&Aogonek;',
  "\x{0105}" => '&aogonek;',
  "\x{0141}" => '&Lstroke;',
  "\x{0142}" => '&lstroke;',
  "\x{0118}" => '&Eogonek;',
  "\x{0119}" => '&eogonek;',
  "\x{0106}" => '&Cacute;',
  "\x{0107}" => '&cacute;',
  "\x{0143}" => '&Nacute;',
  "\x{0144}" => '&nacute;',
  "\x{015a}" => '&Sacute;',
  "\x{015b}" => '&sacute;',
  "\x{0179}" => '&Zacute;',
  "\x{017a}" => '&zacute;',

  "\x{05d0}" => '&alef;',
  "\x{05d1}" => '&bet;',
  "\x{05d2}" => '&gimel;',
  "\x{05d3}" => '&dalet;',
  "\x{05d4}" => '&he;',
  "\x{05d5}" => '&vav;',
  "\x{05d6}" => '&zayin;',
  "\x{05d7}" => '&het;',
  "\x{05d8}" => '&tet;',
  "\x{05d9}" => '&yod;',
  "\x{05da}" => '&fkaf;',
  "\x{05db}" => '&kaf;',
  "\x{05dc}" => '&lamed;',
  "\x{05dd}" => '&fmem;',
  "\x{05de}" => '&mem;',
  "\x{05df}" => '&fnun;',
  "\x{05e0}" => '&nun;',
  "\x{05e1}" => '&samekh;',
  "\x{05e2}" => '&ayin;',
  "\x{05e3}" => '&fpe;',
  "\x{05e4}" => '&pe;',
  "\x{05e5}" => '&ftsadi;',
  "\x{05e6}" => '&tsadi;',
  "\x{05e7}" => '&qof;',
  "\x{05e8}" => '&resh;',
  "\x{05e9}" => '&shin;',
  "\x{05ea}" => '&tav;',

  # <!-- hungaraj -->

  # <!-- evitu, char shajne ne launormaj liternomoj -->
#  "\x{0150}" => '&Odacute;',
#  "\x{0151}" => '&odacute;',
#  "\x{0170}" => '&Udacute;',
#  "\x{0171}" => '&udacute;',

  # <!-- uzu tiujn anstataue -->
  "\x{0150}" => '&Odblac;',
  "\x{0151}" => '&odblac;',
  "\x{0170}" => '&Udblac;',
  "\x{0171}" => '&udblac;',

  # <!-- kimraj -->
  "\x{0176}" => '&Ycirc;',
  "\x{0177}" => '&ycirc;',
  "\x{1e80}" => '&Wgrave;',
  "\x{1e81}" => '&wgrave;',
  "\x{1e82}" => '&Wacute;',
  "\x{1e83}" => '&wacute;',
  "\x{1e84}" => '&Wuml;',
  "\x{1e85}" => '&wuml;',
  "\x{1ef2}" => '&Ygrave;',
  "\x{1ef3}" => '&ygrave;',
  "\x{0174}" => '&Wcirc;',
  "\x{0175}" => '&wcirc;',
  "\x{0178}" => '&Yuml;',
  "\x{00ff}" => '&yuml;',

  # <!-- arabaj/persaj -->
  "\x{064E}\x{0627}" => '&a_fatha_A;',
  "\x{0650}\x{064A}" => '&a_kasra_y;',
  "\x{064F}\x{0648}" => '&a_damma_w;',
  "\x{060C}" => '&a_komo;',
  "\x{061B}" => '&a_punktokomo;',
  "\x{061F}" => '&a_demando;',
  "\x{0621}" => '&a_hamza;',
  "\x{0622}" => '&a_A_madda;',
  "\x{0623}" => '&a_A_hamza_sure;',
  "\x{0624}" => '&a_w_hamza;',
  "\x{0625}" => '&a_A_hamza_sube;',
  "\x{0626}" => '&a_y_hamza;',
  "\x{0627}" => '&a_A;',
  "\x{0628}" => '&a_b;',
  "\x{0629}" => '&a_t_marbuta;',
  "\x{062A}" => '&a_t;',
  "\x{062B}" => '&a_th;',
  "\x{062C}" => '&a_j;',
  "\x{062D}" => '&a_H;',
  "\x{062E}" => '&a_kh;',
  "\x{062F}" => '&a_d;',
  "\x{0630}" => '&a_dh;',
  "\x{0631}" => '&a_r;',
  "\x{0632}" => '&a_z;',
  "\x{0633}" => '&a_s;',
  "\x{0634}" => '&a_sh;',
  "\x{0635}" => '&a_S;',
  "\x{0636}" => '&a_D;',
  "\x{0637}" => '&a_T;',
  "\x{0638}" => '&a_Z;',
  "\x{0639}" => '&a_ayn;',
  "\x{063A}" => '&a_gh;',
  "\x{0640}" => '&a_tatwil;',
  "\x{0641}" => '&a_f;',
  "\x{0642}" => '&a_q;',
  "\x{0643}" => '&a_k;',
  "\x{0644}" => '&a_l;',
  "\x{0645}" => '&a_m;',
  "\x{0646}" => '&a_n;',
  "\x{0647}" => '&a_h;',
  "\x{0648}" => '&a_w;',
  "\x{0649}" => '&a_A_maqsura;',
  "\x{064A}" => '&a_y;',
  "\x{064B}" => '&a_fathatan;',
  "\x{064C}" => '&a_dammatan;',
  "\x{064D}" => '&a_kasratan;',
  "\x{064E}" => '&a_fatha;',
  "\x{064F}" => '&a_damma;',
  "\x{0650}" => '&a_kasra;',
  "\x{0651}" => '&a_shadda;',
  "\x{0652}" => '&a_sukun;',
  "\x{0653}" => '&a_madda_sure;',
  "\x{0654}" => '&a_hamza_sure;',
  "\x{0655}" => '&a_hamza_sube;',
  "\x{0656}" => '&a_A_sube;',
  "\x{0660}" => '&a_0;',
  "\x{0661}" => '&a_1;',
  "\x{0662}" => '&a_2;',
  "\x{0663}" => '&a_3;',
  "\x{0664}" => '&a_4;',
  "\x{0665}" => '&a_5;',
  "\x{0666}" => '&a_6;',
  "\x{0667}" => '&a_7;',
  "\x{0668}" => '&a_8;',
  "\x{0669}" => '&a_9;',
  "\x{066A}" => '&a_procento;',
  "\x{066B}" => '&a_dekumakomo;',
  "\x{066C}" => '&a_milumakomo;',
  "\x{066D}" => '&a_asterisko;',
  "\x{0670}" => '&a_A_sure;',
  "\x{0671}" => '&a_A_wasla;',
  "\x{067E}" => '&f_p;',
  "\x{0686}" => '&f_ch;',
  "\x{0698}" => '&f_zh;',
  "\x{06A9}" => '&f_k;',
  "\x{06AF}" => '&f_g;',
  "\x{06C0}" => '&u_hy;',
  "\x{06CC}" => '&f_y;',
  "\x{06F0}" => '&f_0;',
  "\x{06F1}" => '&f_1;',
  "\x{06F2}" => '&f_2;',
  "\x{06F3}" => '&f_3;',
  "\x{06F4}" => '&f_4;',
  "\x{06F5}" => '&f_5;',
  "\x{06F6}" => '&f_6;',
  "\x{06F7}" => '&f_7;',
  "\x{06F8}" => '&f_8;',
  "\x{06F9}" => '&f_9;',

  # <!-- formatsignoj -->
  "\x{200C}" => '&zwnj;',
  "\x{200D}" => '&zwj;',
  "\x{200E}" => '&lrm;',
  "\x{200F}" => '&rlm;',
  "\x{202A}" => '&lre;',
  "\x{202B}" => '&rle;',
  "\x{202C}" => '&pdf;',
  "\x{202D}" => '&lro;',
  "\x{202E}" => '&rlo;',
  );

  my $regex = join '', map { quotemeta } keys %map;
  $str =~ s{([$regex])}{$map{$1}}gx;

  $str = HTML::Entities::encode_entities_numeric($str, "\x{80}-\x{10FFFF}"); 
  return $str;
}

################################################
## no critic (Modules::ProhibitMultiplePackages)
package HTML::Entities;

{
  ## no critic (TestingAndDebugging::ProhibitNoWarnings)
  no warnings 'redefine';
  sub num_entity {
    my ($char) = @_; return sprintf "&#%u;", ord($char);
  }
  ## use critic
}
1;

